language: julia
sudo: false
os:
  - linux
  - osx
julia:
  - 0.3
  - 0.4
  - 0.5
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("GeoIP"); Pkg.test("GeoIP"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("GeoIP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
